set(MFG_AMPERE_KERNEL_IMAGE "PTX" CACHE STRING "Ampere program: PTX, AUTO or CUBIN")
set_property(CACHE MFG_AMPERE_KERNEL_IMAGE PROPERTY STRINGS PTX AUTO CUBIN)
set(MFG_AMPERE_NATIVE_MANIFEST "" CACHE FILEPATH "Locally generated hash-only native SM86 manifest")
set(MFG_AMPERE_NATIVE_MANIFEST_3109 "" CACHE FILEPATH "Additional exact 310.9 native SM86 manifest")
set(MFG_AMPERE_NATIVE_MANIFEST_ADDITIONAL "" CACHE FILEPATH "Complete additional native SM86 program contracts")
set(MFG_AMPERE_NATIVE_RESOURCES_ADDITIONAL "" CACHE FILEPATH "Hash-bound additional native resource list")
set(MFG_AMPERE_KERNEL_DIRECTORY_ADDITIONAL "" CACHE PATH "Directory containing complete additional SM86 assets")
if(MFG_AMPERE_KERNEL_IMAGE STREQUAL "PTX")
    set(MFG_AMPERE_KERNEL_IMAGE_VALUE 0)
elseif(MFG_AMPERE_KERNEL_IMAGE STREQUAL "AUTO")
    set(MFG_AMPERE_KERNEL_IMAGE_VALUE 1)
elseif(MFG_AMPERE_KERNEL_IMAGE STREQUAL "CUBIN")
    set(MFG_AMPERE_KERNEL_IMAGE_VALUE 2)
else()
    message(FATAL_ERROR "MFG_AMPERE_KERNEL_IMAGE must be PTX, AUTO or CUBIN")
endif()
set(MFG_AMPERE_NATIVE_CACHE_VALUE 0)
if(MFG_AMPERE_NATIVE_MANIFEST)
    if(NOT EXISTS "${MFG_AMPERE_NATIVE_MANIFEST}")
        message(FATAL_ERROR "Explicit native SM86 manifest is missing")
    endif()
    file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/generated")
    configure_file("${MFG_AMPERE_NATIVE_MANIFEST}" "${CMAKE_CURRENT_BINARY_DIR}/generated/ampere_native_manifest.inc" COPYONLY)
    include_directories("${CMAKE_CURRENT_BINARY_DIR}/generated")
    set(MFG_AMPERE_NATIVE_CACHE_VALUE 1)
elseif(MFG_AMPERE_KERNEL_IMAGE STREQUAL "CUBIN")
    message(FATAL_ERROR "CUBIN requires an explicit native SM86 manifest")
endif()
add_compile_definitions(MFG_AMPERE_KERNEL_IMAGE=${MFG_AMPERE_KERNEL_IMAGE_VALUE}
    MFG_AMPERE_NATIVE_CACHE=${MFG_AMPERE_NATIVE_CACHE_VALUE})
set(MFG_AMPERE_NATIVE_CACHE_3109_VALUE 0)
if(MFG_AMPERE_NATIVE_MANIFEST_3109)
    if(NOT MFG_AMPERE_NATIVE_CACHE_VALUE OR NOT EXISTS "${MFG_AMPERE_NATIVE_MANIFEST_3109}")
        message(FATAL_ERROR "The additional 310.9 manifest requires the existing complete manifest and its own file")
    endif()
    configure_file("${MFG_AMPERE_NATIVE_MANIFEST_3109}" "${CMAKE_CURRENT_BINARY_DIR}/generated/ampere_native_manifest_3109.inc" COPYONLY)
    set(MFG_AMPERE_NATIVE_CACHE_3109_VALUE 1)
endif()
add_compile_definitions(MFG_AMPERE_NATIVE_CACHE_3109=${MFG_AMPERE_NATIVE_CACHE_3109_VALUE})
set(MFG_AMPERE_NATIVE_CACHE_ADDITIONAL_VALUE 0)
if(MFG_AMPERE_NATIVE_MANIFEST_ADDITIONAL)
    if(NOT MFG_AMPERE_NATIVE_CACHE_VALUE OR NOT EXISTS "${MFG_AMPERE_NATIVE_MANIFEST_ADDITIONAL}"
            OR NOT EXISTS "${MFG_AMPERE_NATIVE_RESOURCES_ADDITIONAL}")
        message(FATAL_ERROR "Additional native programs require the primary manifest and a hash-bound resource list")
    endif()
    file(READ "${MFG_AMPERE_NATIVE_RESOURCES_ADDITIONAL}" additional_resources)
    string(JSON additional_schema GET "${additional_resources}" schema)
    string(JSON additional_expected GET "${additional_resources}" manifest_sha256)
    file(SHA256 "${MFG_AMPERE_NATIVE_MANIFEST_ADDITIONAL}" additional_actual)
    string(TOUPPER "${additional_actual}" additional_actual)
    if(NOT additional_schema EQUAL 1 OR NOT additional_actual STREQUAL additional_expected)
        message(FATAL_ERROR "Additional native manifest/resource identity mismatch")
    endif()
    configure_file("${MFG_AMPERE_NATIVE_MANIFEST_ADDITIONAL}" "${CMAKE_CURRENT_BINARY_DIR}/generated/ampere_native_manifest_additional.inc" COPYONLY)
    set(MFG_AMPERE_NATIVE_CACHE_ADDITIONAL_VALUE 1)
endif()
add_compile_definitions(MFG_AMPERE_NATIVE_CACHE_ADDITIONAL=${MFG_AMPERE_NATIVE_CACHE_ADDITIONAL_VALUE})

option(MFG_AMPERE_EMBEDDED_KERNELS "Embed the validated SM86 program in the module" OFF)
set(MFG_AMPERE_KERNEL_DIRECTORY "" CACHE PATH "Directory containing the admitted native SM86 assets")
set(MFG_AMPERE_KERNEL_DIRECTORY_3109 "" CACHE PATH "Directory containing the additional admitted 310.9 native SM86 assets")
if(MFG_AMPERE_EMBEDDED_KERNELS)
    if(NOT MFG_AMPERE_NATIVE_CACHE_VALUE OR MFG_AMPERE_KERNEL_IMAGE STREQUAL "PTX")
        message(FATAL_ERROR "Embedded kernels require the exact manifest and AUTO or CUBIN mode")
    endif()
    set(resource "#include <windows.h>\n")
    set(programs legacy)
    if(MFG_AMPERE_NATIVE_CACHE_3109_VALUE)
        list(APPEND programs 3109)
    endif()
    foreach(program IN LISTS programs)
        if(program STREQUAL "3109")
            set(program_manifest "${MFG_AMPERE_NATIVE_MANIFEST_3109}")
            set(program_directory "${MFG_AMPERE_KERNEL_DIRECTORY_3109}")
            set(id 4100)
        else()
            set(program_manifest "${MFG_AMPERE_NATIVE_MANIFEST}")
            set(program_directory "${MFG_AMPERE_KERNEL_DIRECTORY}")
            set(id 4000)
        endif()
        file(READ "${program_manifest}" manifest)
        string(REGEX MATCHALL "\\{\"[0-9A-F]+\", \"[0-9A-F]+\", [0-9]+u\\}" entries "${manifest}")
        list(LENGTH entries count)
        if(NOT count EQUAL 25)
            message(FATAL_ERROR "Expected exactly 25 native kernel manifest entries")
        endif()
        foreach(entry IN LISTS entries)
            string(REGEX REPLACE "^.*\", \"([0-9A-F]+)\", ([0-9]+)u\\}$" "\\1;\\2" fields "${entry}")
            list(GET fields 0 sha)
            list(GET fields 1 bytes)
            set(asset "${program_directory}/${sha}.fatbin")
            if(NOT EXISTS "${asset}")
                message(FATAL_ERROR "Missing admitted kernel: ${sha}")
            endif()
            file(SHA256 "${asset}" actual)
            string(TOUPPER "${actual}" actual)
            file(SIZE "${asset}" actual_bytes)
            if(NOT actual STREQUAL sha OR NOT actual_bytes EQUAL bytes)
                message(FATAL_ERROR "Native kernel identity mismatch: ${sha}")
            endif()
            string(APPEND resource "${id} RCDATA \"${asset}\"\n")
            math(EXPR id "${id} + 1")
            set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${asset}")
        endforeach()
    endforeach()
    if(MFG_AMPERE_NATIVE_CACHE_ADDITIONAL_VALUE)
        string(JSON additional_count LENGTH "${additional_resources}" resources)
        if(additional_count LESS 1 OR additional_count GREATER 1216)
            message(FATAL_ERROR "Additional native resource count is out of bounds")
        endif()
        math(EXPR additional_last "${additional_count} - 1")
        set(additional_ids)
        foreach(index RANGE 0 ${additional_last})
            string(JSON id GET "${additional_resources}" resources ${index} id)
            string(JSON sha GET "${additional_resources}" resources ${index} sha256)
            string(JSON bytes GET "${additional_resources}" resources ${index} bytes)
            string(LENGTH "${sha}" sha_length)
            if(NOT id MATCHES "^[0-9]+$" OR id LESS 4200 OR id GREATER 7337 OR id IN_LIST additional_ids
                    OR NOT sha MATCHES "^[0-9A-F]+$" OR NOT sha_length EQUAL 64
                    OR NOT bytes MATCHES "^[0-9]+$" OR bytes LESS 80 OR bytes GREATER 67108864)
                message(FATAL_ERROR "Invalid or duplicate additional native resource")
            endif()
            list(APPEND additional_ids ${id})
            set(asset "${MFG_AMPERE_KERNEL_DIRECTORY_ADDITIONAL}/${sha}.fatbin")
            if(NOT EXISTS "${asset}")
                message(FATAL_ERROR "Missing additional admitted kernel: ${sha}")
            endif()
            file(SHA256 "${asset}" actual)
            string(TOUPPER "${actual}" actual)
            file(SIZE "${asset}" actual_bytes)
            if(NOT actual STREQUAL sha OR NOT actual_bytes EQUAL bytes)
                message(FATAL_ERROR "Additional native kernel identity mismatch: ${sha}")
            endif()
            string(APPEND resource "${id} RCDATA \"${asset}\"\n")
            set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${asset}")
        endforeach()
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${MFG_AMPERE_NATIVE_RESOURCES_ADDITIONAL}")
    endif()
    set(MFG_AMPERE_KERNEL_RESOURCE "${CMAKE_CURRENT_BINARY_DIR}/generated/ampere_kernels.rc")
    file(WRITE "${MFG_AMPERE_KERNEL_RESOURCE}" "${resource}")
endif()
add_compile_definitions(MFG_AMPERE_EMBEDDED_KERNELS=$<BOOL:${MFG_AMPERE_EMBEDDED_KERNELS}>)
