#pragma once
#ifndef MFG_UNLOCK_AMPERE_MFG
#define MFG_UNLOCK_AMPERE_MFG 0
#endif
#if MFG_UNLOCK_RUNTIME_GPU_SELECTION
#define MFG_PRODUCT "RTXMFG"
#define MFG_PRODUCT_W L"RTXMFG"
#define MFG_CORE_W L"RTXMFGCore.dll"
#define MFG_SHIM_W L"RTXMFG.dll"
#define MFG_CONFIG_W L"RTXMFG-Universal.json"
#define MFG_STATUS_W L"RTXMFG-Universal.status.json"
#define MFG_CONFIG_ENV_W L"RTX_MFG_CONFIG_PATH"
#define MFG_STATUS_ENV_W L"RTX_MFG_STATUS_PATH"
#define MFG_OVERLAY_TITLE "DLSS MFG"
#define MFG_BACKEND_ABI 0x00030009u
#define MFG_STATUS_VERSION "39"
#define MFG_STATUS_VERSION_NUMBER 39u
#define MFG_ENV_PREFIX_W L"RTX_MFG_"
#define MFG_LOG_PREFIX_W L"RTXMFG"
#define MFG_LOG_PREFIX "RTXMFG"
#elif MFG_UNLOCK_AMPERE_MFG
#define MFG_PRODUCT "RTX30MFG"
#define MFG_PRODUCT_W L"RTX30MFG"
#define MFG_CORE_W L"RTX30MFGCore.dll"
#define MFG_SHIM_W L"RTX30MFG.asi"
#define MFG_CONFIG_W L"RTX30MFG-Universal.json"
#define MFG_STATUS_W L"RTX30MFG-Universal.status.json"
#define MFG_CONFIG_ENV_W L"RTX30_MFG_CONFIG_PATH"
#define MFG_STATUS_ENV_W L"RTX30_MFG_STATUS_PATH"
#define MFG_OVERLAY_TITLE "DLSS MFG - Ampere v1.3 experiment"
#define MFG_BACKEND_ABI 0x00300005u
#define MFG_STATUS_VERSION "35"
#define MFG_STATUS_VERSION_NUMBER 35u
#define MFG_ENV_PREFIX_W L"RTX30_MFG_"
#define MFG_LOG_PREFIX_W L"RTX30MFG"
#define MFG_LOG_PREFIX "RTX30MFG"
#else
#define MFG_PRODUCT "RTX40MFG"
#define MFG_PRODUCT_W L"RTX40MFG"
#define MFG_CORE_W L"RTX40MFGCore.dll"
#define MFG_SHIM_W L"RTX40MFG.asi"
#define MFG_CONFIG_W L"RTX40MFG-Universal.json"
#define MFG_STATUS_W L"RTX40MFG-Universal.status.json"
#define MFG_CONFIG_ENV_W L"RTX40_MFG_CONFIG_PATH"
#define MFG_STATUS_ENV_W L"RTX40_MFG_STATUS_PATH"
#define MFG_OVERLAY_TITLE "DLSS MFG"
#define MFG_BACKEND_ABI 0x00030002u
#define MFG_STATUS_VERSION "20"
#define MFG_STATUS_VERSION_NUMBER 20u
#define MFG_ENV_PREFIX_W L"RTX40_MFG_"
#define MFG_LOG_PREFIX_W L"MfgUnlock"
#define MFG_LOG_PREFIX "MfgUnlock"
#endif
